//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./queryengine_types');
//HELPER FUNCTIONS AND STRUCTURES

QueryService_GetCompletion_args = function(args) {
  this.prefix = null;
  this.line = null;
  this.content = null;
  if (args) {
    if (args.prefix !== undefined) {
      this.prefix = args.prefix;
    }
    if (args.line !== undefined) {
      this.line = args.line;
    }
    if (args.content !== undefined) {
      this.content = args.content;
    }
  }
};
QueryService_GetCompletion_args.prototype = {};
QueryService_GetCompletion_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.prefix = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.line = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.content = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QueryService_GetCompletion_args.prototype.write = function(output) {
  output.writeStructBegin('QueryService_GetCompletion_args');
  if (this.prefix !== null && this.prefix !== undefined) {
    output.writeFieldBegin('prefix', Thrift.Type.STRING, 1);
    output.writeString(this.prefix);
    output.writeFieldEnd();
  }
  if (this.line !== null && this.line !== undefined) {
    output.writeFieldBegin('line', Thrift.Type.STRING, 2);
    output.writeString(this.line);
    output.writeFieldEnd();
  }
  if (this.content !== null && this.content !== undefined) {
    output.writeFieldBegin('content', Thrift.Type.STRING, 3);
    output.writeString(this.content);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

QueryService_GetCompletion_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
QueryService_GetCompletion_result.prototype = {};
QueryService_GetCompletion_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QueryService_GetCompletion_result.prototype.write = function(output) {
  output.writeStructBegin('QueryService_GetCompletion_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

QueryServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
QueryServiceClient.prototype = {};
QueryServiceClient.prototype.GetCompletion = function(prefix, line, content, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_GetCompletion(prefix, line, content);
};

QueryServiceClient.prototype.send_GetCompletion = function(prefix, line, content) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetCompletion', Thrift.MessageType.CALL, this.seqid);
  var args = new QueryService_GetCompletion_args();
  args.prefix = prefix;
  args.line = line;
  args.content = content;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

QueryServiceClient.prototype.recv_GetCompletion = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new QueryService_GetCompletion_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetCompletion failed: unknown result');
};
QueryServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
QueryServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

QueryServiceProcessor.prototype.process_GetCompletion = function(seqid, input, output) {
  var args = new QueryService_GetCompletion_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.GetCompletion(args.prefix, args.line, args.content, function (err, result) {
    var result = new QueryService_GetCompletion_result((err != null ? err : {success: result}));
    output.writeMessageBegin("GetCompletion", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

