/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "queryengine_constants.h"

namespace queryengine {

const queryengineConstants g_queryengine_constants;

queryengineConstants::queryengineConstants() {
}

} // namespace

