/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef queryengine_CONSTANTS_H
#define queryengine_CONSTANTS_H

#include "queryengine_types.h"

namespace queryengine {

class queryengineConstants {
 public:
  queryengineConstants();

};

extern const queryengineConstants g_queryengine_constants;

} // namespace

#endif
